import {Colors, Fonts} from 'src/utils';
import {ScaledSheet} from 'react-native-size-matters';
import {Dimensions, Platform} from 'react-native';
const width = Dimensions.get('window').width;
const {fontScale} = Dimensions.get('window');

export default ScaledSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.appColorBackground,
  },
  emptyTxt: {
    letterSpacing: 0.75,
    color: Colors.white,
    fontSize: '20@ms0.3',
    flex: 1,
    fontWeight: '600',
    padding: '0@ms0.3',
    fontFamily: Fonts.Regular,
    alignContent: 'center',
    textAlign: 'center',
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: '40@ms0.3',
  },
  listContiner: {
    paddingRight: '0@ms0.3',
    marginVertical: '0@ms0.3',
    paddingVertical: '4@ms0.3',
  },
  innerContainer: {
    flexDirection: 'row',
    height: fontScale > 1 ? 57 * fontScale : '59@ms0.3',
    elevation: 3,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.6,
    shadowRadius: 3,
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    backgroundColor: '#00000010', // Set a semi-transparent background color
    borderRadius: '44@ms0.3',
    overflow: 'visible',
  },
  timeContainer: {
    backgroundColor: '#21365110', // Set a semi-transparent background color
    alignSelf: 'center',
    paddingHorizontal: '10@ms0.3',
    borderRadius: '20@ms0.3',
    height: fontScale > 1 ? 19 * fontScale : '20@ms0.3',
    elevation: 3,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 3,
    shadowOpacity: 1,
    marginTop: '4@ms0.3',
    marginLeft: Platform.OS === 'android' ? '36@ms0.3' : '44@ms0.3',
  },
  liveMainContainer: {
    width: fontScale > 1 ? (width / 5) * fontScale : width / 5,
    justifyContent: 'center',
    alignContent: 'center',
    height: fontScale > 1 ? 20 * fontScale : '34@ms0.3',
    marginTop: '2@ms0.3',
  },
  liveTimeContainer: {
    backgroundColor: '#21365110', // Set a semi-transparent background color
    paddingHorizontal: '16@ms0.3',
    marginLeft: '8@ms0.3',
    borderRadius: '20@ms0.3',
    height: fontScale > 1 ? 20 * fontScale : '22@ms0.3',
    justifyContent: 'center',
    alignSelf: 'center',
    elevation: 3,
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 3,
    shadowOpacity: 1,
  },
  timeSliderContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    height: fontScale > 1 ? 20 * fontScale : '34@ms0.3',
  },
  timeSliderInnerContainer: {
    flex: 1,
  },
  rightIconStyle: {
    width: width / 5,
    justifyContent: 'center',
    alignContent: 'center',
    height: fontScale > 1 ? 20 * fontScale : '34@ms0.3',
    marginTop: '2@ms0.3',
  },
  nextContainer: {
    backgroundColor: Colors.brandBlue,
    paddingHorizontal: '18@ms0.3',
    marginRight: '5@ms0.3',
    marginLeft: '5@ms0.3',
    borderRadius: '20@ms0.3',
    width: fontScale > 1 ? 24 * fontScale : '26@ms0.3',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  rightIcon: {
    height: '10@ms0.3',
    width: '16@ms0.3',
  },
  imageContainer: {
    height: fontScale > 1 ? 57 * fontScale : '59@ms0.3',
    width: fontScale > 1 ? 55 * fontScale : '57@ms0.3',
    backgroundColor: Colors.mediumBlue,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '1@ms0.3',
  },
  imageIcon: {
    height: '48@ms0.3',
    width: '47@ms0.3',
  },
  userNameContainer: {
    paddingStart: '6@ms0.3',
    position: 'absolute',
    left: '60@ms0.3',
    width: '82%',
  },
  leftContainer: {
    flex: 1,
    backgroundColor: Colors.darkGrey,
  },
  rightContainer: {
    flex: 1,
    backgroundColor: Colors.blueGrey,
  },
  sliderActiveTimeTxt: {
    fontSize: '13@ms0.3',
    fontWeight: '800',
    lineHeight: '22@ms0.3',
    color: Colors.white,
    fontFamily: Fonts.Regular,
    fontStyle: 'italic',
  },
  sliderInactiveTimeTxt: {
    fontSize: '13@ms0.3',
    lineHeight: '20@ms0.3',
    color: Colors.white,
  },
  titleTxt: {
    fontSize: '16@ms0.3',
    fontWeight: '800',
    // lineHeight: '18@ms0.3',
    color: Colors.white,
    fontFamily: Fonts.Regular,
  },
  eventTxt: {
    fontSize: '13@ms0.3',
    fontWeight: '400',
    lineHeight: '17@ms0.3',
    color: Colors.white,
    fontFamily: Fonts.Regular,
    marginTop: '2@ms0.3',
  },
  eventDateTxt: {
    fontSize: '13@ms0.3',
    fontWeight: '400',
    lineHeight: '18@ms0.3',
    color: Colors.white,
    fontFamily: Fonts.Regular,
  },
  sliderContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.mediumBlue,
    height: fontScale > 1 ? (width / 4.4) * fontScale : '100@ms0.3',
  },
  sliderInnerContainer: {
    // flex: 1,
    marginHorizontal: '7@ms0.3',
    marginVertical: '10@ms0.3',
    justifyContent: 'center',
  },
  sliderImageBackground: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sliderInnerMainContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: '2@ms0.3',
    borderColor: '#004EBC',
    height: fontScale > 1 ? (width / 4.8) * fontScale : width / 5.1,
    borderRadius: fontScale > 1 ? 21 * fontScale : '18@ms0.3',
    width: fontScale > 1 ? (width / 4.8) * fontScale : width / 5.1,
    overflow: 'visible',
  },
  sliderIcon: {
    height: fontScale > 1 ? 25 * fontScale : '28@ms0.3',
    width: fontScale > 1 ? 25 * fontScale : '28@ms0.3',
    paddingVertical: '12@ms0.3',
    tintColor: Colors.white,
    marginTop: '10@ms0.3',
  },
  sliderTxt: {
    fontSize: '12@ms0.3',
    fontWeight: '900',
    lineHeight: '24@ms0.3',
    color: Colors.white,
    fontFamily: Fonts.Bold,
    fontStyle: 'italic',
    elevation: 3,
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 8,
    textShadowColor: '#000000',
    marginBottom: '3@ms0.3',
  },
  rectangle2: {
    position: 'absolute',
    left: Platform.OS === 'android' ? -5 : -5,
    top: -4.5,
    // height: '94@ms0.3',
    height: fontScale > 1 ? (width / 4.9) * fontScale : width / 4.7 - 1,
    // width: width / 4.3,
    width: fontScale > 1 ? (width / 4.9) * fontScale : width / 4.71,
    borderRadius: fontScale > 1 ? 19 * fontScale : '20@ms0.3',
    borderWidth: '3@ms0.3',
    borderColor: Colors.brandBlue,
    opacity: 0.3,
  },
});
