export default {
  connecting: 'Connecting You To:',
  all: 'ALL',
  pro: 'PRO',
  college: 'COLLEGE',
  esports: 'ESPORTS',
  watchOptions: 'Watch Options',
  connectToWatch: 'Connect to Watch on These Apps or Services',
  connectToWatchFuture: 'This Event Begins Streaming on',
  connectToWatchEmpty: 'There are no direct connections available for this event.',
  otherWays: 'Other ways to watch...',
  settings: 'Settings',
  legal: 'Legal',
  reportProblem: 'Report a Problem',
  termUse: 'Terms of Use',
  privacyPolicy: 'Privacy Policy/Info We Collect',
  californiaPolicy: 'Supplemental Notice',
  watchNow: 'Go!',
  personalInfo: 'Personal Info',
  changePassword: 'Change Password',
  saveThisCard: 'Save this card for future payments',
  sportsStreamingApps: 'Sports & Streaming Apps',
  aboutWatchSports: 'About WatchSports',
  manageFavorite: 'Manage your favorite sports',
  eventReminder: 'Set Event Reminders',
  enableNotification: 'Enable Notifications',
  eventReminderNotifications: 'Allow Watch Sports to send notifications',
  enableNotificationDesc: "Watch Sports requires notification permission, Please go to settings and enable Notifications",
  no: 'No',
  countryRegion: 'Country or Region',
  yes: 'Yes',
  accessFeaturesGuide: 'Create an account to customize your experience.',
  accessFeatures: 'You’ll need to register to access these features.',
  noThanks: 'No Thanks',
  upgrade: 'Upgrade',
  createFreeAccount: 'Create a Free Account',
  logout: 'Logout',
  wantToLogout: 'Are you sure you want to logout?',
  updatePassword: 'Update Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  saveChanges: 'Save Changes',
  cancel: 'Cancel',
  alert: 'Alert',
  checkout: 'Checkout',
  cardInformation: 'Card Information',
  payUsing: 'or pay using',
  choosePlan: 'Choose Your Plan',
  filterFvrt: 'Filter the guide by your \nfavorite sports.',
  upgradeAccount: 'Upgrade your account \nand get access to \nthese exclusive features:',
  sportStreaming: 'Sports & Streaming Apps',
  sportStreamingDes: 'Please share how you watch to help us improve our service',
  alertDes: 'Are you sure you want to cancel your account? This will erase your favorites and notification preferences.',
  emptyGuideList: "There are no live events in our schedule during this time period. Tap 'Live' above to see live event listings or swipe right to see upcoming event listings",
  emptySearchList: "Search by Event, Team, League, or Sport to Find Upcoming Event Schedule and Watch Information",
  emptyEventsSearchList: "There are no live events in our schedule this week that match your search. Try another search or tap ‘Cancel’ above to return the Event Guide.",
  welcome: "Welcome to",
  liveSportsEventGuide: "Live Sports Event Guide",
  welcomeCreateAccount: "Create an account for fast access to Pro, College, Olympic, and Esports event information & viewing",
  login: "Login",
  resetPassword: "Reset Password",
  continueGuest: "Continue as Guest",
  email: "Email",
  password: "Password",
  signIn: "Sign In",
  forgotPassword: "Forgot Password?",
  dontAccount: "Don't have an account?",
  signUp: "Sign Up",
  firstName: "First Name",
  lastName: "Last Name",
  confirmPassword: "Confirm Password",
  signupTerm: "Email Opt-in lorem ipsum dolor sit amet consectetur.",
  haveRead: "I have read and agree to the",
  termsofService: "Terms of Use",
  privacyPolicy2: "Privacy Policy",
  search: "Search",
  continue: "Continue",
  pleaseCheckInbox: "Please check your inbox to verify your account",
  pleaseCheckInboxReset: "Please check your inbox to reset the password",
  liveNow: "LIVE NOW!",
  connecttoWatch: "Connect to Watch",
  optHere: "SMS opt-in here",
  month: "$__amount__/month",
  year: "$__amount__/year",
  mobileNumber: "Mobile Number",
  cardNumber: "Card Number",
  zip: "Zip",
  unitedStates: "United States",
  CVV: "CVV",
  womenWorld: "Women’s World Cup Qualifier",
  sharingYourLocation: "Sharing your location allows us to surface the most relevant event listings in your area",
  youMustBe: "You must be at least 14 years of age to register.",
  preferredPronouns: "Select your preferred pronouns",
  pronouns: "Pronouns",
  birthdate: "Birthdate",
  zipCode: "Zip Code",
  code: "Code",
  weJustNeed: "We just need a few more details to configure your account",
  welcomeName: "Welcome, __NAME__!",
  cancelAccount: "Cancel Account",
  saveChanges: "Save Changes",
  submit: 'Submit',
  passwordResetSuccessfully: 'Password reset successfully. You can now log in with your new password.',
  passwordResetInitiation: 'Password reset initiation successfully. Check your email for instructions.',
  alreadyAccount: "Already have an account?",
  profileCompleted: 'Profile Completed Successfully!!',
  emptyFavoriteSportList: "You haven't added any favorite sports yet. Tap 'Star Icon' to choose your favorite sports and get personalized event listings.",
  notSupportedNotifications: "This device does not supports Notifications",
};
