export default {
  connecting: 'Connecting You To:',
  all: 'ALL',
  pro: 'PRO',
  college: 'COLLEGE',
  esports: 'ESPORTS',
  watchOptions: 'Watch Options',
  connectToWatch: 'Connect to Watch on These Apps or Services',
  connectToWatchFuture:'This Event Begins Streaming on',
  connectToWatchEmpty: 'There are no direct connections available for this event.',
  otherWays: 'Other ways to watch...',
  settings: 'Settings',
  legal: 'Legal',
  reportProblem: 'Report a Problem',
  termUse: 'Terms of Use',
  privacyPolicy: 'Privacy Policy/Info We Collect',
  californiaPolicy: 'California Policy',
  watchNow: 'Watch Now',
  personalInfo: 'Personal Info',
  changePassword: 'Change Password',
  savethisCard: 'Save this card for future payments',
  sportsStreamingApps: 'Sports & Streaming Apps',
  aboutWatchSports: 'About WatchSports',
  manageFavorite: 'Manage your favorite sports',
  eventReminder: 'Set Event Reminders',
  eventReminderNotifications: 'Allow Watch Sports to send notifications',
  no: 'No',
  countryRegion: 'Country or Region',
  yes: 'Yes',
  accessFeatures: 'You’ll need to register to access these features.',
  noThanks: 'No Thanks',
  createFreeAccount: 'Create Free Account',
  logout: 'Logout',
  wantToLogout: 'Are you sure you want to logut?',
  updatePassword: 'Update Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  saveChanges: 'Save Changes',
  cancel: 'Cancel',
  alert: 'Alert',
  checkout: 'Checkout',
  cardInformation: 'Card Information',
  payusing: 'or pay using',
  choosePlan: 'Choose Your Plan',
  filterFvrt: 'Filter the guide by your favorite sports.',
  upgradeAccount: 'Upgrade your account and get access to these exclusive features:',
  sportStreaming: 'Sports & Streaming Apps',
  sportStreamingDes: 'Please share how you watch to help us improve our service',
  alertDes: 'Are you sure you want to cancel your account? This will erase your favorites and notification preferences.',
  emptyGuideList: "There are no live events in our schedule during this time period. Tap 'Live' above to see live event listings or swipe right to see upcoming event listings",
  emptySearchList: "Search by Event, Team, League or Sport to Find Upcoming Event Schedule and Watch Information",
  emptyEventsSearchList: "There are no live events in our schedule today that match your search. Try another search or tap ‘Cancel’ above to return the Event Guide.",
  search: "Search",
  liveNow: "LIVE NOW!",
  womenWorld: "Women’s World Cup Qualifier",
};
